service: serverless-todo-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  environment:
    TODOS_TABLE: ${self:service}-${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
          Resource: !GetAtt TodosTable.Arn

functions:
  createTodo:
    handler: src/handlers/createTodo.handler
    events:
      - http:
          path: /todos
          method: post
          cors: true

  listTodos:
    handler: src/handlers/listTodos.handler
    events:
      - http:
          path: /todos
          method: get
          cors: true

  getTodo:
    handler: src/handlers/getTodo.handler
    events:
      - http:
          path: /todos/{id}
          method: get
          cors: true

  updateTodo:
    handler: src/handlers/updateTodo.handler
    events:
      - http:
          path: /todos/{id}
          method: put
          cors: true

  deleteTodo:
    handler: src/handlers/deleteTodo.handler
    events:
      - http:
          path: /todos/{id}
          method: delete
          cors: true

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TODOS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST 